name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hello! It looks like this is your first issue — thanks for helping out! Please let the developers know if you have any questions.'
        pr-message: 'Hello! It looks like this is your first issue — thanks for contributing! Please let the other developers know if you have any questions.'
